---

- name: Create remote directory
  file: path=/flask state=directory mode=0755


- name: Clone git repository
  git: >
    dest=/flask
    repo=https://github.com/rguittou/docker-webserver-flask/
    update=no
  sudo: yes

- name: Launch flask website
  command: python3 /flask/hello.py "runserver" -h 0.0.0.0 -p 5000



